"""init

Revision ID: 2b1ff0126b4b
Revises: 
Create Date: 2025-08-08 12:02:17.094647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1ff0126b4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_orders_user_salon_id'), table_name='orders')
    op.add_column('salon', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salon', 'timezone')
    op.create_index(op.f('idx_orders_user_salon_id'), 'orders', ['user_salon_id'], unique=False)
    # ### end Alembic commands ###
