"""Add is_super_admin and is_salon_admin to User

Revision ID: 5d334f0f1eee
Revises: 9327819cd17c
Create Date: 2025-07-10 12:30:19.006793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d334f0f1eee'
down_revision: Union[str, Sequence[str], None] = '9327819cd17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_super_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('is_salon_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_salon_admin')
    op.drop_column('user', 'is_super_admin')
    # ### end Alembic commands ###
